import Head from "next/head";
import styles from "@/styles/Home.module.css";
import LandingMain from "@/src/components/landing/LandingMain";
import LandingHeader from "@/src/components/landing/LandingHeader";

export default function Home() {
  return (
    <>
      <Head>
        <title>taskify-당신의 일정을 관리하세요</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LandingHeader />
      <LandingMain />

      <footer className={styles.footer}></footer>
    </>
  );
}
